on:
  push:
    branches:
    - master
  pull_request:
name: Go Test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race ./...
      - run: go vet ./...
      - run: go mod verify
